[env:wt32-eth01]
platform = espressif32
board = wt32-eth01
framework = arduino
src_dir = .
src_filter = +<*.ino>

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0
    adafruit/Adafruit BusIO @ ^1.16

monitor_speed = 115200
