[platformio]
src_dir = .


[env:wt32-eth01]
platform = espressif32
board = wt32-eth01
framework = arduino


lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6
    paulstoffregen/OneWire @ ^2.3
    milesburton/DallasTemperature @ ^3.9

monitor_speed = 115200
